name: Test
on: 
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        submodules: true
   
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go  

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: test
      run: go test -v
